# Generated by Django 3.0.6 on 2020-07-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Blogpost',
        ),
    ]
