# Generated by Django 3.0.6 on 2020-06-22 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_orderupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderupdate',
            old_name='updte_id',
            new_name='upadte_id',
        ),
        migrations.RenameField(
            model_name='orderupdate',
            old_name='updte_desc',
            new_name='update_desc',
        ),
    ]
